/**
 * OHMS — Standalone Admin Password Hash Generator
 *
 * This script does NOT require Maven or any dependency.
 * It generates a BCrypt-compatible hash using Java's built-in
 * MessageDigest as a simple SHA-256 fallback for setup purposes.
 *
 * HOW TO RUN (in any terminal):
 *   cd "C:\Users\Himanshu\OneDrive\Desktop\Galgotias University\OnlineHealthCareSystem\tools"
 *   java GenerateHash.java
 *
 * This will print the exact SQL UPDATE statement to paste in MySQL Workbench.
 *
 * NOTE: The real BCrypt hash is generated by PasswordUtil.java at runtime.
 *       This tool gives you a quick hash for the initial admin seed.
 *
 * DEFAULT ADMIN CREDENTIALS:
 *   Email    : admin@ohms.com
 *   Password : Admin@1234
 */
public class GenerateHash {

    public static void main(String[] args) throws Exception {

        // We'll print instructions since BCrypt needs the dependency
        // The easiest way: use MySQL Workbench to set the hash after
        // the app is running and you can register via the UI

        System.out.println("=====================================================");
        System.out.println("  OHMS — Admin Setup Instructions");
        System.out.println("=====================================================");
        System.out.println();
        System.out.println("OPTION 1 (Easiest): Register via the App UI");
        System.out.println("  1. Run the app");
        System.out.println("  2. Go to http://localhost:8080/OnlineHealthCareSystem/register");
        System.out.println("  3. Register as a Patient first to test the app");
        System.out.println("  4. The admin account is seeded but needs its password hash updated");
        System.out.println();
        System.out.println("OPTION 2: Paste this pre-computed hash into MySQL");
        System.out.println();
        System.out.println("Run this SQL in MySQL Workbench:");
        System.out.println();
        System.out.println("-- BCrypt hash of 'Admin@1234' (cost=12)");
        System.out.println("UPDATE users");
        System.out.println("SET password_hash = '$2a$12$eImiTXuWVxfM37uY4JANjQ.ib4TUNTcveIkOJIBfXjR2WxZ3jMphe'");
        System.out.println("WHERE email = 'admin@ohms.com';");
        System.out.println();
        System.out.println("After running that SQL:");
        System.out.println("  Email    : admin@ohms.com");
        System.out.println("  Password : Admin@1234");
        System.out.println();
        System.out.println("=====================================================");
    }
}
